import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, Play, Pause, Sparkles, Library, BarChart3, Plus, Heart, History, Wand2, Users, CreditCard, Music2, ListMusic, Radio, Settings, ChevronRight } from 'lucide-react';
import { tracks, playlists, aiPrompts } from './data/tracks';
import './styles.css';

function Sidebar({page,setPage}){ const items=[['home',Music2,'Listen'],['ai',Sparkles,'AI Assistant'],['sets',ListMusic,'DJ Set Builder'],['dashboard',BarChart3,'Dashboard'],['workspace',Users,'Workspace'],['billing',CreditCard,'Billing'],['settings',Settings,'Settings']]; return <aside className="sidebar"><div className="brand"><div className="logo">V</div><div><b>Viewly</b><span>Music AI SaaS</span></div></div><nav>{items.map(([id,Icon,label])=><button key={id} onClick={()=>setPage(id)} className={page===id?'active':''}><Icon size={18}/>{label}</button>)}</nav><div className="sideCard"><b>AI copilote actif</b><p>Analyse les sons, aide tes playlists, tes sets DJ et ton contenu.</p></div></aside>}
function Topbar(){return <header className="topbar"><div className="search"><Search size={18}/><input placeholder="Search tracks, playlists, moods, BPM..."/></div><button className="ghost">Import YouTube</button><button className="primary"><Plus size={18}/>New playlist</button></header>}
function Player({track,playing,setPlaying}){return <div className="player"><div className="disc" style={{background:track.color}}></div><div className="now"><b>{track.title}</b><span>{track.artist} - {track.mood}</span></div><button className="play" onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play/>}</button><div className="progress"><span></span></div><button className="ghost"><Heart size={17}/></button></div>}
function Listen(){ const [current,setCurrent]=useState(tracks[0]); const [playing,setPlaying]=useState(false); return <main className="content"><section className="hero"><div><p className="eyebrow">Music first. AI everywhere.</p><h1>Écoute, organise et améliore tes musiques avec une IA qui t’aide pour tout.</h1><p>Viewly garde l’idée principale : écouter de la musique. L’IA sert à trouver, classer, recommander, préparer des sets et créer du contenu plus vite.</p><div className="actions"><button className="primary"><Play size={18}/>Start listening</button><button className="secondary"><Wand2 size={18}/>Ask AI</button></div></div><div className="heroCard"><Radio size={34}/><h3>Smart Radio</h3><p>Auto-mix mood, BPM et énergie selon ton objectif.</p><div className="meter"><span style={{width:'78%'}}></span></div></div></section><Player track={current} playing={playing} setPlaying={setPlaying}/><section className="grid two"><div className="panel"><h2>Recommended tracks</h2>{tracks.map(t=><button className="track" key={t.id} onClick={()=>setCurrent(t)}><div className="cover" style={{background:t.color}}></div><div><b>{t.title}</b><span>{t.artist} - {t.bpm} BPM - {t.mood}</span></div><em>{t.duration}</em></button>)}</div><div className="panel"><h2>AI help for this session</h2>{aiPrompts.map(p=><div className="prompt" key={p}><Sparkles size={17}/>{p}<ChevronRight size={16}/></div>)}<div className="insight"><b>Suggestion IA</b><p>Ton set peut commencer à 120 BPM, monter vers 128 BPM, puis finir avec un morceau nostalgique pour maximiser la rétention.</p></div></div></section></main>}
function AIAssistant(){ const [q,setQ]=useState(''); const answer=useMemo(()=> q?`Plan IA pour: ${q}\n1. Trouver 12 titres proches.\n2. Classer par mood, BPM et énergie.\n3. Créer une playlist écoutable.\n4. Proposer un ordre DJ set + idées TikTok/Reels.`:'', [q]); return <main className="content"><div className="pageHead"><h1>AI Music Assistant</h1><p>L’IA ne remplace pas la musique : elle aide à chercher, comprendre, classer et créer plus vite.</p></div><div className="aiBox"><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Ex: trouve moi des sons style Yann Muller, disco, été, 125 BPM..."/><button className="primary"><Sparkles size={18}/>Generate</button></div>{answer&&<pre className="answer">{answer}</pre>}<div className="grid three">{['Music discovery','Playlist strategy','Content ideas'].map(x=><div className="panel mini" key={x}><Sparkles/><h3>{x}</h3><p>Prompts prêts à utiliser pour accélérer ton workflow.</p></div>)}</div></main>}
function Sets(){return <main className="content"><div className="pageHead"><h1>DJ Set Builder</h1><p>Prépare l’ordre parfait avec BPM flow, énergie et notes.</p></div><div className="timeline">{tracks.map((t,i)=><div className="slot" key={t.id}><span>{i+1}</span><b>{t.title}</b><small>{t.bpm} BPM - Energy {t.energy}</small><div className="energy"><i style={{width:t.energy+'%'}}></i></div></div>)}</div></main>}
function Dashboard(){return <main className="content"><div className="pageHead"><h1>Dashboard SaaS</h1><p>Vue produit pour suivre usage, playlists, exports et croissance.</p></div><div className="stats"><div><b>1,248</b><span>plays</span></div><div><b>86</b><span>AI searches</span></div><div><b>19</b><span>playlists</span></div><div><b>7</b><span>exports</span></div></div><section className="panel"><h2>Playlists</h2>{playlists.map(p=><div className="row" key={p.id}><b>{p.name}</b><span>{p.type}</span><span>{p.tracks} tracks</span><em>{p.growth}</em></div>)}</section></main>}
function SimplePage({title,desc}){return <main className="content"><div className="pageHead"><h1>{title}</h1><p>{desc}</p></div><div className="grid two"><div className="panel"><h2>Ready module</h2><p>Structure frontend prête à brancher à Supabase, Stripe et API IA.</p></div><div className="panel"><h2>Next action</h2><p>Connecte tes clés dans .env puis lance npm run dev.</p></div></div></main>}
function App(){ const [page,setPage]=useState('home'); const pages={home:<Listen/>,ai:<AIAssistant/>,sets:<Sets/>,dashboard:<Dashboard/>,workspace:<SimplePage title="Workspace" desc="Multi-projets, clients, équipes et playlists partagées."/>,billing:<SimplePage title="Billing" desc="Plans Free, Creator, Pro DJ et Agency prêts pour Stripe."/>,settings:<SimplePage title="Settings" desc="Compte, préférences IA, sources musicales et sécurité."/>}; return <div className="app"><Sidebar page={page} setPage={setPage}/><div className="main"><Topbar/>{pages[page]}</div></div>}

createRoot(document.getElementById('root')).render(<App/>);
